---
  - name: create group apis
    group: name=apis state=present
    become: yes

  - name: create user osu_apis
    user: name=osu_apis comment="OSU APIs" group=apis password={{ user_psw }}
    become: yes

  - name: create apis directory
    file: path=/apis state=directory group=apis owner=osu_apis mode=0770 recurse=yes
    become: yes

  - name: create apis/apis directory
    file: path=/apis/apis state=directory group=apis owner=osu_apis mode=0770 recurse=yes
    become: yes

  - name: create apis/keytool_files directory
    file: path=/apis/keytool_files state=directory group=apis owner=osu_apis mode=0555 recurse=yes
    become: yes

  - name: create apis/logs directory
    file: path=/apis/logs state=directory group=apis owner=osu_apis mode=0770 recurse=yes
    become: yes
